# Generated by Django 6.0.3 on 2026-04-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('name_normalized', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('description_normalized', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
